<?php
/* Integration checks against Dolibarr 24. CLI only; all fixtures rolled back.
 * R&R Technology, 2026. GPL-3.0-or-later. */
if (PHP_SAPI!=='cli') { http_response_code(404); exit; }
define('NOLOGIN',1); define('NOREQUIREMENU',1); define('NOREQUIREHTML',1); define('NOREQUIREAJAX',1);
require '/var/www/html/master.inc.php';
require_once __DIR__.'/../class/rrrenting.class.php';
require_once DOL_DOCUMENT_ROOT.'/societe/class/societe.class.php';
require_once DOL_DOCUMENT_ROOT.'/contrat/class/contrat.class.php';
$user=new User($db); $user->fetch('',getenv('DOLI_ADMIN_LOGIN') ?: 'admin'); $user->getrights();
$rr=new RrRenting($db,$user,$conf->entity); $passed=0;
function check($ok,$msg) { global $passed; if (!$ok) { throw new RuntimeException($msg); } $passed++; print "PASS ".$msg."\n"; }
function rejected($fn,$msg) {
    global $db;
    $db->query('SAVEPOINT expected_failure');
    $caught=false;
    try { $fn(); } catch (RuntimeException $e) { $caught=true; }
    $db->query('ROLLBACK TO SAVEPOINT expected_failure');
    check($caught,$msg);
}
function productFixture($ref,$type) {
    global $db,$user;
    $p=new Product($db); $p->ref=$ref; $p->label=$ref; $p->type=$type; $p->status=1; $p->status_buy=1;
    $p->price=100; $p->price_base_type='HT'; $p->tva_tx=0; $p->status_batch=$type?0:2;
    $id=$p->create($user);
    if ($id<=0) { throw new RuntimeException('Fixture product: '.$p->error.' '.implode('; ',$p->errors)); }
    return $id;
}
$db->begin();
try {
    $rr->setup(); $c=$rr->config();
    $tag='RRTEST-'.bin2hex(random_bytes(4));
    $product=productFixture($tag.'-PC',0); $service=productFixture($tag.'-SERVICE',1);
    $soc=new Societe($db); $soc->name=$tag; $soc->client=1; $soc->status=1; $soc->code_client='auto';
    check($soc->create($user)>0,'customer fixture created');
    $contract=new Contrat($db); $contract->socid=$soc->id; $contract->date_contrat=dol_now(); $contract->commercial_signature_id=$user->id; $contract->commercial_suivi_id=$user->id;
    check($contract->create($user)>0,'native contract created');
    check($contract->addline('Renting test',100,1,0,0,0,$service,0,dol_now(),dol_now()+86400)>0,'native service attached to contract');
    check($contract->validate($user)>0,'native contract validated');
    $series=array($tag.'-001',$tag.'-002');
    foreach($series as $serial) {
        $m=new MouvementStock($db);
        check($m->reception($user,$product,$c->sale,1,100,'Renting integration test',0,0,$serial)>0,'serialized stock received');
    }
    $a=$rr->enroll($product,$series[0]); $b=$rr->enroll($product,$series[1]);
    check($a>0 && $b>0,'two assets enrolled by native transfer');
    $total=$rr->one("SELECT SUM(reel) qty FROM ".$db->prefix()."product_stock WHERE fk_product=".$product);
    check((float)$total->qty===2.0,'enrollment preserves total stock');
    rejected(function()use($rr,$product,$series){$rr->enroll($product,$series[0]);},'duplicate enrollment rejected');
    $today=dol_print_date(dol_now(),'%Y-%m-%d'); $end=date('Y-m-d',strtotime($today.' +2 days'));
    $contractLine=$rr->one('SELECT rowid FROM '.$db->prefix().'contratdet WHERE fk_contrat='.(int)$contract->id)->rowid;
    check($contract->updateline($contractLine,'Two serialized units',100,2,0,strtotime($today),strtotime($end),0)>0,'unreserved contractual conditions can be edited');
    rejected(function()use($rr,$soc,$contract,$contractLine,$product,$a){$rr->reserveFromContract($soc->id,$contract->id,$contractLine,$product,array($a));},'contract quantity rejects incomplete selection');
    rejected(function()use($rr,$soc,$contract,$contractLine,$service,$a,$b){$rr->reserveFromContract($soc->id,$contract->id,$contractLine,$service,array($a,$b));},'equipment must be a serialized physical product');
    $bound=$rr->reserveFromContract($soc->id,$contract->id,$contractLine,$product,array($a,$b));
    $boundBooking=$rr->booking($bound);
    check($boundBooking->date_start===$today && $boundBooking->date_end===$end,'reservation inherits contractual dates');
    rejected(function()use($rr,$soc,$contract,$contractLine,$product,$a,$b){$rr->reserveFromContract($soc->id,$contract->id,$contractLine,$product,array($a,$b));},'same contractual commitment cannot be reserved twice');
    check($contract->deleteLine($contractLine,$user)<0,'native contract line deletion blocked while reserved');
    $db->query('SAVEPOINT contract_edit');
    check($contract->updateline($contractLine,'Reduced quantity',100,1,0,strtotime($today),strtotime($end),0)<0,'native contract quantity modification blocked while reserved');
    $db->query('ROLLBACK TO SAVEPOINT contract_edit');
    $db->query('SAVEPOINT contract_drift');
    $rr->query('UPDATE '.$db->prefix().'contratdet SET qty=3 WHERE rowid='.(int)$contractLine);
    rejected(function()use($rr,$bound){$rr->checkout($bound);},'delivery rejects a contract changed outside normal controls');
    $db->query('ROLLBACK TO SAVEPOINT contract_drift');
    $db->query('SAVEPOINT bound_delivery');
    $rr->checkout($bound);
    check($rr->booking($bound)->status==='active','contract-bound reservation delivers complete equipment set');
    check($contract->deleteLine($contractLine,$user)<0,'contract line remains protected after delivery');
    $db->query('ROLLBACK TO SAVEPOINT bound_delivery');
    $rr->cancel($bound);
    check($contract->updateline($contractLine,'Two units',100,2,0,strtotime($today),strtotime($end),0)>0,'contract line unlocked after cancellation');
    require_once __DIR__.'/../lib/recurring_billing.php';
    $db->query('SAVEPOINT billing_workflow');
    $bill=new RrBilling($db,$user,$conf->entity);
    check($bill->periods('2026-01-31','2026-04-30')===3,'month-end schedule follows native calendar');
    check($bill->periods('2026-02-28','2026-03-30')===1,'February end uses native next month end');
    $billingEnd=date('Y-m-d',strtotime($today.' +3 months'));
    $newLine=$contract->addline('Monthly renting',100,2,13,0,0,$service,0,strtotime($today),strtotime($billingEnd));
    check($newLine>0,'monthly contract line created');
    $billingBooking=$rr->reserveFromContract($soc->id,$contract->id,$newLine,$product,array($a,$b));
    $terms=$rr->one('SELECT rowid FROM '.$db->prefix().'c_payment_term WHERE active=1 ORDER BY rowid LIMIT 1')->rowid;
    $before=(int)$rr->one('SELECT COUNT(*) qty FROM '.$db->prefix().'facture')->qty;
    $template=$bill->createSchedule($billingBooking,true,$terms);
    check($template>0,'native template created directly from renting');
    check((int)$rr->one('SELECT COUNT(*) qty FROM '.$db->prefix().'facture')->qty===$before,'no technical source invoice remains');
    $rec=new FactureRec($db);$rec->fetch($template);
    check((int)$rec->nb_gen_max===3 && (float)$rec->lines[0]->qty===2.0,'monthly count and equipment quantity inherited');
    check((int)$rec->suspended===1,'billing waits for equipment delivery');
    $db->query('SAVEPOINT cancelled_billing');
    $rr->cancel($billingBooking); $rec->fetch($template);
    check((int)$rec->suspended===1 && $rr->one('SELECT state FROM '.$rr->table('billing').' WHERE fk_booking='.(int)$billingBooking)->state==='paused','cancellation keeps scheduled invoices stopped');
    $db->query('ROLLBACK TO SAVEPOINT cancelled_billing');
    $rec->fetch($template);
    rejected(function()use($bill,$billingBooking,$terms){$bill->createSchedule($billingBooking,true,$terms);},'duplicate billing schedule rejected');
    check(rrRunRecurringBilling($db,$conf->entity,$template)===0,'no invoice before delivery');
    $db->query('SAVEPOINT manual_billing');
    $manual=new Facture($db); $manual->fac_rec=$template; $manual->fk_fac_rec_source=$template; $manual->socid=$soc->id; $manual->date=dol_now(); $manual->type=0;
    check($manual->create($user)<0,'manual generation of managed template blocked');
    $db->query('ROLLBACK TO SAVEPOINT manual_billing');
    $db->query('SAVEPOINT template_edit');
    $rec->title='Unauthorized change';
    check($rec->update($user)<0,'native editing of managed template blocked');
    $db->query('ROLLBACK TO SAVEPOINT template_edit');
    $rr->checkout($billingBooking);
    check(rrRunRecurringBilling($db,$conf->entity,$template)===1,'first monthly draft generated after delivery');
    $firstInvoice=$rr->one('SELECT rowid,fk_statut,total_ttc FROM '.$db->prefix().'facture WHERE fk_fac_rec_source='.(int)$template);
    check((int)$firstInvoice->fk_statut===0 && abs((float)$firstInvoice->total_ttc-226)<0.001,'generated draft preserves quantity and VAT');
    check(rrRunRecurringBilling($db,$conf->entity,$template)===0,'repeated worker does not duplicate monthly invoice');
    $delivered=$rr->rows('SELECT rowid FROM '.$rr->table('line').' WHERE fk_booking='.(int)$billingBooking.' ORDER BY rowid');
    $db->query('SAVEPOINT total_return');
    $allIds=array_map(function($l){return (int)$l->rowid;},$delivered);
    rejected(function()use($rr,$billingBooking,$delivered){$rr->receiveAll($billingBooking,array($delivered[0]->rowid));},'total return rejects incomplete or stale list');
    $rr->query("UPDATE ".$rr->table('asset')." SET status='review' WHERE rowid=".(int)$b);
    rejected(function()use($rr,$billingBooking,$allIds){$rr->receiveAll($billingBooking,$allIds);},'failed total return rolls back all previous receipts');
    check($rr->asset($a)->status==='out' && !$rr->one('SELECT date_return FROM '.$rr->table('line').' WHERE rowid='.(int)$delivered[0]->rowid)->date_return,'failed total return preserves first delivered unit');
    $rr->query("UPDATE ".$rr->table('asset')." SET status='out' WHERE rowid=".(int)$b);
    $rr->receiveAll($billingBooking,$allIds);
    $rec->fetch($template);
    check($rr->booking($billingBooking)->status==='closed' && (int)$rec->suspended===1,'total receipt closes renting and stops future billing');
    check($rr->asset($a)->status==='review' && $rr->asset($b)->status==='review','all units received for technical diagnosis');
    rejected(function()use($rr,$billingBooking,$allIds){$rr->receiveAll($billingBooking,$allIds);},'repeated total receipt rejected');
    $db->query('ROLLBACK TO SAVEPOINT total_return');
    $db->query('SAVEPOINT staged_replacement');
    $staged=$rr->receiveIncident($billingBooking,$delivered[0]->rowid,'Intermittent shutdown, diagnosis pending');
    check($rr->asset($a)->status==='review' && $rr->asset($a)->item_condition==='pending','incident reception defers diagnosis to technician');
    $rec->fetch($template);
    check((int)$rec->suspended===0 && $rr->booking($billingBooking)->status==='active','incident reception preserves billing and renting');
    rejected(function()use($rr,$billingBooking,$delivered){$rr->receiveIncident($billingBooking,$delivered[0]->rowid,'Duplicate');},'duplicate incident reception rejected');
    rejected(function()use($rr,$billingBooking,$staged,$a){$rr->replaceEquipment($billingBooking,$staged,$a,'Not diagnosed');},'unit awaiting diagnosis cannot be redelivered');
    $rr->inspect($a,'repair','damaged','Fault verified by technician');
    $rr->inspect($a,'available','good','Repair complete and tested');
    $again=$rr->replaceEquipment($billingBooking,$staged,$a,'Same repaired serial returned to customer');
    check($again!=$delivered[0]->rowid && $rr->asset($a)->status==='out','same repaired serial is redelivered with separate history');
    check((int)$rr->one('SELECT COUNT(*) qty FROM '.$rr->table('line').' WHERE fk_booking='.(int)$billingBooking.' AND fk_asset='.(int)$a)->qty===2,'previous delivery retained in history');
    rejected(function()use($rr,$billingBooking,$staged,$a){$rr->replaceEquipment($billingBooking,$staged,$a,'Duplicate');},'completed staged replacement cannot deliver twice');
    $waiting=$rr->receiveIncident($billingBooking,$again,'Another reported fault');
    $rr->receive($billingBooking,$delivered[1]->rowid);
    check($rr->booking($billingBooking)->status==='partial','pending replacement prevents closure after last physical return');
    $rr->finishIncident($billingBooking,$waiting,'Customer cancels remaining service');
    $rec->fetch($template);
    check($rr->booking($billingBooking)->status==='closed' && (int)$rec->suspended===1,'definitive cancellation of pending replacement closes renting and suspends invoices');
    rejected(function()use($rr,$billingBooking,$waiting,$a){$rr->replaceEquipment($billingBooking,$waiting,$a,'After cancellation');},'cancelled replacement cannot deliver');
    $db->query('ROLLBACK TO SAVEPOINT staged_replacement');
    $db->query('SAVEPOINT replacement_workflow');
    $spareSerial=$tag.'-SPARE';
    $movement=new MouvementStock($db);
    check($movement->reception($user,$product,$c->sale,1,100,'Replacement fixture',0,0,$spareSerial)>0,'replacement stock received');
    $spare=$rr->enroll($product,$spareSerial);
    $incident=$rr->reportIncident($billingBooking,$delivered[0]->rowid,'Customer reports intermittent failure');
    rejected(function()use($rr,$billingBooking,$delivered){$rr->reportIncident($billingBooking,$delivered[0]->rowid,'Duplicate');},'duplicate open incident rejected');
    $rec->fetch($template);
    check((int)$rec->suspended===0,'report alone does not pause invoicing');
    rejected(function()use($rr,$billingBooking,$incident,$b){$rr->replaceEquipment($billingBooking,$incident,$b,'Busy unit');},'already delivered replacement rejected');
    $conflict=$rr->reserve($soc->id,$contract->id,$service,$today,$end,array($spare));
    rejected(function()use($rr,$billingBooking,$incident,$spare){$rr->replaceEquipment($billingBooking,$incident,$spare,'Reserved elsewhere');},'replacement with overlapping reservation rejected');
    $rr->cancel($conflict);
    $rr->query('UPDATE '.$db->prefix().'product_batch pb JOIN '.$db->prefix().'product_stock ps ON ps.rowid=pb.fk_product_stock SET pb.qty=0 WHERE ps.fk_product='.(int)$product.' AND ps.fk_entrepot='.(int)$c->available.' AND pb.batch='.$rr->quote($spareSerial));
    rejected(function()use($rr,$billingBooking,$incident,$spare){$rr->replaceEquipment($billingBooking,$incident,$spare,'Missing physical stock');},'failed replacement rolls back both movements');
    check($rr->asset($a)->status==='out' && !$rr->one('SELECT date_return FROM '.$rr->table('line').' WHERE rowid='.(int)$delivered[0]->rowid)->date_return,'failed exchange preserves original delivered unit');
    $restored=$rr->one('SELECT pb.qty FROM '.$db->prefix().'product_batch pb JOIN '.$db->prefix().'product_stock ps ON ps.rowid=pb.fk_product_stock WHERE ps.fk_product='.(int)$product.' AND ps.fk_entrepot='.(int)$c->customer.' AND pb.batch='.$rr->quote($series[0]));
    check((float)$restored->qty===1.0,'failed exchange restores source stock');
    $rr->query('UPDATE '.$db->prefix().'product_batch pb JOIN '.$db->prefix().'product_stock ps ON ps.rowid=pb.fk_product_stock SET pb.qty=1 WHERE ps.fk_product='.(int)$product.' AND ps.fk_entrepot='.(int)$c->available.' AND pb.batch='.$rr->quote($spareSerial));
    $newLine=$rr->replaceEquipment($billingBooking,$incident,$spare,'Received faulty unit and delivered replacement');
    check($rr->asset($a)->status==='review' && $rr->asset($spare)->status==='out','replacement moves faulty unit to review and spare to customer');
    check($rr->one('SELECT status FROM '.$rr->table('incident').' WHERE rowid='.(int)$incident)->status==='replaced','incident records completed exchange');
    check((int)$rr->one('SELECT COUNT(*) qty FROM '.$rr->table('line').' WHERE fk_booking='.(int)$billingBooking.' AND date_return IS NULL')->qty===2,'replacement preserves number of units delivered');
    $rec->fetch($template);
    check((int)$rec->suspended===0 && (float)$rec->lines[0]->qty===2.0 && (int)$rec->nb_gen_done===1,'replacement preserves billing state quantity and generated count');
    check($rr->booking($billingBooking)->status==='active','replacement does not create partial return state');
    rejected(function()use($rr,$billingBooking,$incident,$spare){$rr->replaceEquipment($billingBooking,$incident,$spare,'Repeated');},'repeated replacement rejected');
    rejected(function()use($rr,$a){$rr->inspect($a,'available','damaged','Still broken');},'faulty return cannot rejoin fleet');
    $rr->inspect($a,'repair','damaged','Fault confirmed, repair required');
    $rr->inspect($a,'available','good','Component repaired and load test passed');
    check($rr->asset($a)->status==='available','repaired unit can rejoin fleet directly');
    $rr->inspect($a,'sale','good','Retired from rental fleet after review');
    check($rr->asset($a)->status==='sale','reviewed repaired equipment can leave fleet for sale');
    $rr->enroll($product,$series[0]);
    check($rr->asset($a)->status==='available','previously used equipment can be enrolled again');
    $rr->receive($billingBooking,$newLine,'good');
    $rr->receive($billingBooking,$delivered[1]->rowid,'good');
    check($rr->booking($billingBooking)->status==='closed','substitute can be returned normally and booking closes');
    check((float)$rr->one('SELECT SUM(reel) qty FROM '.$db->prefix().'product_stock WHERE fk_product='.(int)$product)->qty===3.0,'exchange and repair preserve total physical stock');
    $db->query('ROLLBACK TO SAVEPOINT replacement_workflow');
    $rr->receive($billingBooking,$delivered[0]->rowid,'damaged');
    $rec->fetch($template);
    check((int)$rec->suspended===1,'partial damaged return pauses future invoices');
    $next=date('Y-m-d',$rec->date_when);
    $bill->resume($billingBooking,$next,true,'Customer agrees to one remaining unit');
    $rec->fetch($template);
    check((float)$rec->lines[0]->qty===1.0 && (int)$rec->suspended===0,'future quantity adjusted to remaining equipment');
    check(abs((float)$rr->one('SELECT total_ttc FROM '.$db->prefix().'facture WHERE rowid='.(int)$firstInvoice->rowid)->total_ttc-226)<0.001,'already generated invoice unchanged by adjustment');
    $rr->receive($billingBooking,$delivered[1]->rowid,'good');
    $rec->fetch($template);
    check((int)$rec->suspended===1,'final return stops future billing');
    rejected(function()use($bill,$billingBooking,$next){$bill->resume($billingBooking,$next,false,'Invalid restart');},'closed renting cannot resume billing');
    $db->query('ROLLBACK TO SAVEPOINT billing_workflow');
    rejected(function()use($rr,$soc,$contract,$service,$today,$end){$rr->reserve($soc->id,$contract->id,$service,$end,$today,array(0));},'invalid dates rejected');
    rejected(function()use($rr,$soc,$contract,$service,$today,$end,$a){$rr->reserve($soc->id+999999,$contract->id,$service,$today,$end,array($a));},'wrong customer rejected');
    $booking=$rr->reserve($soc->id,$contract->id,$service,$today,$end,array($a,$b));
    rejected(function()use($rr,$soc,$contract,$service,$today,$end,$a){$rr->reserve($soc->id,$contract->id,$service,$today,$end,array($a));},'overlapping reservation rejected');
    rejected(function()use($rr,$a){$rr->inspect($a,'sale','good','test');},'reserved asset cannot be moved to sale');
    $future=$rr->reserve($soc->id,$contract->id,$service,date('Y-m-d',strtotime($end.' +1 day')),date('Y-m-d',strtotime($end.' +3 days')),array($a));
    check($future>0,'nonoverlapping future reservation accepted');
    rejected(function()use($rr,$future){$rr->checkout($future);},'early delivery rejected');
    $rr->cancel($future);
    // Force the second transfer to fail and verify the first is undone by the workflow itself.
    $rr->query("UPDATE ".$db->prefix()."product_batch pb JOIN ".$db->prefix()."product_stock ps ON ps.rowid=pb.fk_product_stock SET pb.qty=0 WHERE ps.fk_product=".$product." AND pb.batch=".$rr->quote($series[1]));
    $failed=false;
    try { $rr->checkout($booking); } catch (RuntimeException $ex) { $failed=true; }
    check($failed && $rr->asset($a)->status==='available','failed multi-equipment checkout rolls back earlier asset updates');
    $aStock=$rr->one("SELECT pb.qty FROM ".$db->prefix()."product_batch pb JOIN ".$db->prefix()."product_stock ps ON ps.rowid=pb.fk_product_stock WHERE ps.fk_entrepot=".(int)$c->available." AND ps.fk_product=".$product." AND pb.batch=".$rr->quote($series[0]));
    check((float)$aStock->qty===1.0,'failed checkout restores original warehouse stock');
    $rr->query("UPDATE ".$db->prefix()."product_batch pb JOIN ".$db->prefix()."product_stock ps ON ps.rowid=pb.fk_product_stock SET pb.qty=1 WHERE ps.fk_product=".$product." AND pb.batch=".$rr->quote($series[1]));
    $rr->checkout($booking);
    check($rr->asset($a)->status==='out','checkout marks asset delivered');
    rejected(function()use($rr,$booking){$rr->checkout($booking);},'repeated checkout rejected');
    $m=new MouvementStock($db);
    $db->query('SAVEPOINT stock_guard');
    $result=$m->livraison($user,$product,$c->customer,1,0,'Unauthorized sale','',0,0,$series[0]);
    check($result<0,'native sale from renting warehouse blocked by hook');
    $db->query('ROLLBACK TO SAVEPOINT stock_guard');
    $lines=$rr->rows("SELECT * FROM ".$rr->table('line')." WHERE fk_booking=".$booking." ORDER BY rowid");
    $rr->receive($booking,$lines[0]->rowid,'good');
    check($rr->booking($booking)->status==='partial','partial return tracked');
    check($rr->asset($a)->status==='review','return goes to review instead of immediately available');
    rejected(function()use($rr,$booking,$lines){$rr->receive($booking,$lines[0]->rowid,'good');},'duplicate return rejected');
    rejected(function()use($rr,$a){$rr->inspect($a,'available','damaged','test');},'damaged equipment cannot become available');
    $rr->inspect($a,'available','good','Inspection passed');
    $rr->receive($booking,$lines[1]->rowid,'damaged');
    $rr->inspect($b,'repair','damaged','Repair required');
    check($rr->booking($booking)->status==='closed','all returns close the renting');
    check($rr->asset($b)->status==='repair','damaged equipment retained in repair');
    $rr->inspect($b,'available','good','Repair completed');
    $rr->inspect($a,'sale','worn','Reviewed for used sale');
    check($rr->asset($a)->status==='sale','uncommitted reviewed asset transferred to sale');
    $total=$rr->one("SELECT SUM(reel) qty FROM ".$db->prefix()."product_stock WHERE fk_product=".$product);
    check((float)$total->qty===2.0,'full workflow preserves exactly two physical units');
    require_once DOL_DOCUMENT_ROOT.'/commande/class/commande.class.php';
    $oversell=new Commande($db); $oversell->socid=$soc->id; $oversell->date=dol_now();
    check($oversell->create($user)>0,'native sales order created');
    check($oversell->addline('Hardware',100,2,0,0,0,$product)>0,'draft sale can be prepared');
    $db->query('SAVEPOINT order_reject');
    $result=$oversell->valid($user);
    check($result<0 && strpos($oversell->error.' '.implode(' ',$oversell->errors),'Stock de venta insuficiente')!==false,'sale cannot count renting stock when validating order');
    $db->query('ROLLBACK TO SAVEPOINT order_reject');
    $sale=new Commande($db); $sale->socid=$soc->id; $sale->date=dol_now();
    check($sale->create($user)>0,'second native sales order created');
    check($sale->addline('Hardware',100,1,0,0,0,$product)>0,'sale line for available unit created');
    check($sale->valid($user)>0,'sale within RR-VENTA stock is allowed');
    rejected(function()use($rr,$product,$series){$rr->enroll($product,$series[0]);},'stock committed to validated sale cannot move to renting');
    $other=new RrRenting($db,$user,$conf->entity+999);
    rejected(function()use($other,$a){$other->asset($a);},'cross-entity asset lookup blocked');
    $restricted=new User($db); $restricted->id=999999; $restricted->admin=0;
    $limited=new RrRenting($db,$restricted,$conf->entity);
    rejected(function()use($limited,$product,$series){$limited->enroll($product,$series[0]);},'write operation without permission rejected');
    $limitedBilling=new RrBilling($db,$restricted,$conf->entity);
    rejected(function()use($limitedBilling,$booking){$limitedBilling->createSchedule($booking,true);},'billing creation requires business and invoice permissions');
    print "SUCCESS: ".$passed." integration checks. Fixtures rolled back.\n";
} catch(Throwable $ex) {
    fwrite(STDERR,"FAIL: ".$ex->getMessage()."\n".$ex->getTraceAsString()."\n");
    $db->query('ROLLBACK'); $db->transaction_opened=0; exit(1);
} finally { $db->query('ROLLBACK'); $db->transaction_opened=0; }
